version: '3'
services:
  envoy:
    image: envoyproxy/envoy:latest
    container_name: envoyproxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      #- ./key:/key
      #- ./pem:/pem
      - ./envoy.log:/var/log/envoy.log
    ports:
      - "443:443"
      - "10000:10000"
    expose:
      - "443"
      - "10000"
